name: CI

on:
  push:
    paths:
    - 'dockerfiles/**'
    - 'scripts/deploy.py'
    - 'scripts/create-layer.sh'
    - 'tests/*'
    - '.github/workflows/ci.yml'
    branches:
    - master
    tags:
    - '*'
  pull_request:

env:
  GDAL_VERSION: 3.8.2
  GDAL_VERSION_TAG: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3 click

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          load: true
          file: dockerfiles/Dockerfile
          build-args: |
            GDAL_VERSION=${{ env.GDAL_VERSION }}
          tags: ghcr.io/${{ github.repository_owner }}/lambda-gdal:${{ env.GDAL_VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          docker run \
            --platform=linux/amd64 \
            --entrypoint bash \
            -v ${{ github.workspace }}:/local \
            --rm ghcr.io/${{ github.repository_owner }}/lambda-gdal:${{ env.GDAL_VERSION_TAG }} \
            /local/tests/tests.sh

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags') && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          file: dockerfiles/Dockerfile
          build-args: |
            GDAL_VERSION=${{ env.GDAL_VERSION }}
          push: true
          cache-from: type=gha
          tags: ghcr.io/${{ github.repository_owner }}/lambda-gdal:${{ env.GDAL_VERSION_TAG }}

      - name: Build Runtime and Push
        run: |
          runtimes='3.9 3.10 3.11'
          for runtime in ${runtimes}; do
            docker build \
              --platform=linux/amd64 \
              --build-arg GDAL_VERSION=${{ env.GDAL_VERSION_TAG }} \
              --build-arg RUNTIME_VERSION=${runtime} \
              -f dockerfiles/runtimes/python \
              -t ghcr.io/${{ github.repository_owner }}/lambda-gdal:${{ env.GDAL_VERSION_TAG }}-python${runtime} .
            docker push ghcr.io/${{ github.repository_owner }}/lambda-gdal:${{ env.GDAL_VERSION_TAG }}-python${runtime}
          done
